encyclopedia/urls.py
from django.urls import path

from . import views

app_name = "wikipedia"
urlpatterns = [
    path("", views.index, name="index"),
    path("search", views.search, name="search"),
    path("add/",  views.add, name="add"),
    path("edit", views.edit, name="edit"),
    path("<str:title>", views.entry, name="entry"),
]

wiki/urls.py
from django.contrib import admin
from django.urls import include, path


urlpatterns = [
    path('admin/', admin.site.urls),
    path('wiki/', include("encyclopedia.urls"))
]

encyclopedia/models.py
from django.db import models


# Create your models here.

encyclopedia/views.py
from django.shortcuts import render
from markdown2 import Markdown
from django import forms
from django.http import HttpResponseRedirect
from django.urls import reverse
import secrets
from django.core.exceptions import ValidationError

from . import util

markdown_conversion = Markdown()


def validator_title_unique(text):
    if util.get_entry(text) is not None:
        raise ValidationError("Post with that title already exists.")


class NewWikiEntry(forms.Form):
    new_entry_title = forms.CharField(max_length=100, validators=[
                                      validator_title_unique], label="Title")
    new_entry_content = forms.CharField(
        widget=forms.Textarea(attrs={'class': 'textarea_content'}), label="Content")


class EditWikiEntry(forms.Form):
    edit_entry_title = forms.CharField(max_length=100, label="Title ")
    edit_entry_content = forms.CharField(
        widget=forms.Textarea(attrs={'class': 'textarea_content'}), label="Content")


def index(request):
    return render(request, "encyclopedia/index.html", {
        "entries": util.list_entries(),
        "random_entry": secrets.choice(util.list_entries())
    })


def entry(request, title):
    entry = util.get_entry(title)
    if entry == None:
        return render(request, "encyclopedia/404.html", {
            "entry": entry,
            "entry_title": title,
            "random_entry": secrets.choice(util.list_entries())
        })
    else:
        entry_html = markdown_conversion.convert(entry)
        return render(request, "encyclopedia/entry.html", {
            "entry": entry_html,
            "entry_title": title,
            "random_entry": secrets.choice(util.list_entries())
        })


def search(request):
    if request.method == "GET":
        param = request.GET.get("q")
        entry = util.get_entry(param)
        entry_titles = util.list_entries()
        search_results = []
        if entry == None:
            for entry_title in entry_titles:
                if param in entry_title:
                    search_results += [entry_title]
                    break
            if search_results == []:
                search_results = 0
            return render(request, "encyclopedia/search.html", {
                "param": param,
                "search_results": search_results,
                "entry": entry,
                "random_entry": secrets.choice(util.list_entries())
            })
        else:
            return HttpResponseRedirect(param)


def add(request):
    if request.method == "POST":
        form = NewWikiEntry(request.POST)
        if form.is_valid():
            content = form.cleaned_data["new_entry_content"]
            title = form.cleaned_data["new_entry_title"]
            word = "# "
            if word in title:
                title = title.lstrip(word)
            content_title = f"# {title}\n\n" + content
            util.save_entry(title, content_title)
            return HttpResponseRedirect("/wiki/" + title)
        else:
            return render(request, "encyclopedia/add.html", {"form": form,
                                                             "random_entry": secrets.choice(util.list_entries())})
    else:
        return render(request, "encyclopedia/add.html", {"form": NewWikiEntry(), "random_entry": secrets.choice(util.list_entries())})


def edit(request):
    if request.method == "POST":
        form = EditWikiEntry(request.POST)
        if form.is_valid():
            content = form.cleaned_data["edit_entry_content"]
            title = form.cleaned_data["edit_entry_title"]
            word = "# "
            if word in title:
                title = title.lstrip(word)
            util.save_entry(title, content)
            return HttpResponseRedirect("/wiki/" + title)
        else:
            edit_title = request.GET.get("title")
            edit_form = EditWikiEntry(initial={'edit_entry_title': request.GET.get(
                "title"), 'edit_entry_content': util.get_entry(edit_title)})
            return render(request, "encyclopedia/edit.html", {
                "form": edit_form,
                "random_entry": secrets.choice(util.list_entries())
            })
    else:
        edit_title = request.GET.get("title")
        edit_form = EditWikiEntry(initial={'edit_entry_title': request.GET.get(
            "title"), 'edit_entry_content': util.get_entry(edit_title)})
        return render(request, "encyclopedia/edit.html", {
            "form": edit_form,
            "random_entry": secrets.choice(util.list_entries())
        })

encyclopedia/templates/encyclopedia/add.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
Wiki: {{entry_title}}
{% endblock %}

{% block body %}
<h1>Add New Entry Page</h1>

<form action="{% url 'wikipedia:add' %}" method="post" class="add_new_entry">
    {% csrf_token %}
    <div class="entry_form">{{ form }}</div>
    <input type="submit" class="btn btn-primary">
</form>
{% endblock %}

encyclopedia/templates/encyclopedia/edit.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
Wiki: {{entry_title}}
{% endblock %}

{% block body %}
<h1>Edit Wiki Entry</h1>

<form action="{% url 'wikipedia:edit' %}" method="post" class="edit_entry">
    {% csrf_token %}
    <div class="entry_form">{{ form }}</div>
    <input type="submit" class="btn btn-primary">
</form>


{% endblock %}

encyclopedia/templates/encyclopedia/entry.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
Wiki: {{entry_title}}
{% endblock %}

{% block body %}

{{entry|safe}}

<div class="btn_edit"><a href="{% url 'wikipedia:edit' %}?title={{entry_title}}"">Edit Page</a></div>
{% endblock %}

encyclopedia/templates/encyclopedia/index.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
Encyclopedia
{% endblock %}

{% block body %}
<h1>All Pages</h1>

<ul class="ul">
    {% for entry in entries %}
    <li class="no-bullets"><a href={{entry}}>{{ entry }}</a></li>
    {% endfor %}
</ul>

{% endblock %}

encyclopedia/templates/encyclopedia/layout.html
{% load static %}

<!DOCTYPE html>

<html lang="en">

<head>
    <title>{% block title %}{% endblock %}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <link href="{% static 'encyclopedia/styles.css' %}" rel="stylesheet">
</head>

<body>
    <div class="wrapper row">
        <div class="col-md-3 col-lg-3">
            <aside id="sidebar">

                <div class="sidebar-logo">
                    <h3>Wiki</h3>
                    <div class="horizontal_line"></div>
                </div>
                <ul class="sidebar-nav">
                    <li class="sidebar-item">
                        <a href="{% url 'wikipedia:index' %}" class="sidebar-link">
                            <span>Home</span>
                        </a>
                    </li>
                    <li class="sidebar-item">
                        <a href="{% url 'wikipedia:add' %}" class="sidebar-link">
                            <span>Create New Page</span>
                        </a>
                    </li>
                    <li class="sidebar-item">
                        <a href="{% url 'wikipedia:index'%}{{random_entry}}" class="sidebar-link">
                            <span>Random Page</span>
                        </a>
                    </li>
                </ul>
                <div class="sidebar-footer">
                    <form action="{% url 'wikipedia:search' %}" method="get" class="d-flex" role="search">
                        {% csrf_token %}
                        <input class="form-control me-2" type="text" name="q" placeholder="Search Encyclopedia">
                        <input type="submit" class="btn btn-outline-light btn-sm">
                    </form>
                </div>
        </div>
        </aside>
        {% block nav %}
        {% endblock %}

        <div class=" col-md-9 col-lg-9">
            <div class="main">
                {% block body %}
                {% endblock %}
            </div>
        </div>
    </div>


</body>

</html>

encyclopedia/templates/encyclopedia/search.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
Wiki: {{entry_title}}
{% endblock %}

{% block body %}
<h1>Search</h1>
<p>You searched for: "{{param}}".</p>

{% if search_results == 0 %}
<p>We couldn't find any result, please try again or <a href="{% url 'wikipedia:add' %}">Creat a new page</a></p>
{% else %}
<p>We could not find an exact match. Did you mean:</p>
<ul> {% for result in search_results %}
    <li><a href={{result}}>{{result}}</a></li>
</ul>

{% endfor %}
{% endif %}
{% endblock %}